server:
  port: 6450
  servlet:
    context-path: /

spring:
  # master 数据源配置
  master:
    datasource:
      url: jdbc:postgresql://localhost:5432/city_park
      username: postgres
      password: sorft
      driver-class-name: org.postgresql.Driver
      #second 数据源配置
  second:
    datasource:
      url: jdbc:postgresql://localhost:5432/offroad_parking
      username: postgres
      password: sorft
      driver-class-name: org.postgresql.Driver
